language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

install:
  - composer install --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs
